### PR TITLE
Added Part, Motor and Lidar classes - Also includes dev-areeb

### PR DESCRIPTION
**Pull request by TSlaven19**

### CODE REVIEW

**Comment by TSlaven19** [comment]
As stated in the last commit, I'll explain why I wrote Part the way I did.

Since we don't want to have to re-establish the rel_x and rel_y vars in each child of Part (which would be dumb because that defeats the purpose of having a Part class), we rely on the Python super() powers (badum-tisss). That allows us to do the following.
```python
# Where parts is a list of instantiated child classes of part
for part in parts:
    print(Part.get_rel_x(part), Part.get_rel_y(part))
```

**Comment by TSlaven19** [comment]
~~Do you want me to go back and add the ability for the input of ints in the place of floats for the classes I wrote?~~
Nevermind, I did it.

**Comment by Areeb-M** [comment]
I was going to say yes, but I see you've already gone ahead and done so. Thanks!

**Review by Areeb-M — APPROVED** [review]
I think all of it looks great. I'll probably refactor the Rover class to not have such verbose type checking in the next iteration cycle.

**Pull request merged**
